version: "3"

services:
  schaakcompetitie-web-c:
    image: minor2020.azurecr.io/dc-schaakcompetitie-web:1
    depends_on:
      - schaakcompetitie-api-c
    networks:
      - SchaakNet
    ports:
      - 5000:80
    environment:
      apiUrl: http://schaakcompetitie-api-c

  schaakcompetitie-api-c:
    image: minor2020.azurecr.io/dc-schaakcompetite-api:1
    networks:
      - SchaakNet
    ports:
      - 5005:80
    environment:
      connectionString: Server=schaakcompetitiesqlserver;Database=SchaakDB;User=sa;Password=Secret_123

  schaakcompetitiesqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    networks:
      - SchaakNet
    environment:
      - SA_PASSWORD=Secret_123
      - ACCEPT_EULA=Y
  
networks:
  SchaakNet:
