apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
  connection-string: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXNlcnZpY2U=
  exchange: RGFubnk=