apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    service: rabbitmq-service
spec:
  selector:
    service: rabbitmq
  ports:
    - name: rabbitmq
      port: 5672
    - name: management
      port: 15672