apiVersion : apps/v1
kind: Deployment
metadata:
  name: schaakwebservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schaakwebservice
  template:
    metadata:
      labels:
        app: schaakwebservice
    spec:
      imagePullSecrets:
        - name: minordockersecret
      containers:
        - name: schaakwebservice
          image: minor2020.azurecr.io/dc-schaakcompetitie-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: 
            limits: 
              cpu: 60m 
              memory: 256Mi 
            requests: 
              cpu: 30m 
              memory: 128Mi
          env:              
            - name: ConnectionStrings__MySql
              valueFrom:
                secretKeyRef:
                  name: schaakwebservice-secret
                  key: connection-string
            - name: ConnectionStrings__RabbitMQ
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: connection-string
            - name: Eventbus__Exchange
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: exchange
            - name: PROXY_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: schaakwebservice-configmap
                  key: proxyprefix